site_name: Bildung 6.0


repo_url: https://gitlab.ti.bfh.ch/bildung6/bildung6
site_url: https://bildung6.pages.ti.bfh.ch/bildung6/
edit_uri: edit/main/docs/

markdown_extensions:
  - footnotes
  - abbr
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
        - name: yaml
          class: yaml
          format: superfences.fence_code_format

plugins:
  - search
  - macros

hooks:
  - my_hooks.py

theme:
  custom_dir: docs/overrides
  language: de
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.sections
    - social
    - content.code.annotate
    - content.code.copy
  name: material
  palette:
    primary: #4051b5
    accent: #4051b5
  favicon: images/favicon.png
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  - stylesheets/extra.css?v=1.4
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/extra.js?v=1.3
extra:
  social:
    - icon: simple/creativecommons
      link: /bildung6/projekt/#lizenz
      name: CC BY-SA 4.0 International
